"""create missing_track table

Revision ID: 02cfda8ae0ce
Revises: 855efacd231b
Create Date: 2026-08-18 05:40:57.016845

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02cfda8ae0ce"
down_revision: str | Sequence[str] | None = "855efacd231b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "missing_track",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sync_track_id", sa.Integer(), nullable=False),
        sa.Column("itunes_track_id", sa.String(), nullable=True),
        sa.Column("itunes_url_auto", sa.String(), nullable=True),
        sa.Column("itunes_url_chosen", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sync_track_id"],
            ["sync_track.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sync_track_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("missing_track")
    # ### end Alembic commands ###
