"""create playlist_link sync_session sync_track tables

Revision ID: 855efacd231b
Revises: f2a9c1b47e30
Create Date: 2026-08-17 20:54:26.807121

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "855efacd231b"
down_revision: str | Sequence[str] | None = "f2a9c1b47e30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "playlist_link",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("spotify_playlist_id", sa.String(), nullable=False),
        sa.Column("rb_playlist_id", sa.String(), nullable=True),
        sa.Column("rb_playlist_name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_applied_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("spotify_playlist_id"),
    )
    op.create_table(
        "sync_session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("playlist_link_id", sa.Integer(), nullable=False),
        sa.Column("spotify_snapshot_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["playlist_link_id"],
            ["playlist_link.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sync_track",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sync_session_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("spotify_track_id", sa.String(), nullable=True),
        sa.Column("isrc", sa.String(), nullable=True),
        sa.Column("artist", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("rb_content_id", sa.String(), nullable=True),
        sa.Column("match_score", sa.Float(), nullable=True),
        sa.Column("candidates", sa.JSON(), nullable=False),
        sa.Column("matched_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sync_session_id"],
            ["sync_session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sync_track")
    op.drop_table("sync_session")
    op.drop_table("playlist_link")
    # ### end Alembic commands ###
