"""create enriched_genre enrichment_state tables

Revision ID: 897efaa0742a
Revises: 7c1cc1025c1f
Create Date: 2026-08-18 15:38:13.091967

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "897efaa0742a"
down_revision: str | Sequence[str] | None = "7c1cc1025c1f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "enriched_genre",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rb_content_id", sa.String(), nullable=False),
        sa.Column("genre", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_enriched_genre_rb_content_id"), "enriched_genre", ["rb_content_id"], unique=False
    )
    op.create_table(
        "enrichment_state",
        sa.Column("rb_content_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("attempted_at", sa.DateTime(), nullable=True),
        sa.Column("last_source", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("rb_content_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("enrichment_state")
    op.drop_index(op.f("ix_enriched_genre_rb_content_id"), table_name="enriched_genre")
    op.drop_table("enriched_genre")
    # ### end Alembic commands ###
