"""create booking profile and structure tables

Revision ID: 8cd0cf8178d6
Revises: 897efaa0742a
Create Date: 2026-08-18 16:38:09.740211

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8cd0cf8178d6"
down_revision: str | Sequence[str] | None = "897efaa0742a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "booking_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("bpm_min", sa.Integer(), nullable=True),
        sa.Column("bpm_max", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "booking_profile_genre_tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("tag", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["booking_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "structure",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("booking_profile_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_applied_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["booking_profile_id"],
            ["booking_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "structure_node",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("structure_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("set_phase", sa.String(), nullable=True),
        sa.Column("rb_ref", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["structure_node.id"],
        ),
        sa.ForeignKeyConstraint(
            ["structure_id"],
            ["structure.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "structure_track",
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("rb_content_id", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("origin", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["structure_node.id"],
        ),
        sa.PrimaryKeyConstraint("node_id", "rb_content_id"),
    )
    op.create_table(
        "suggestion_dismissal",
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column("rb_content_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["structure_node.id"],
        ),
        sa.PrimaryKeyConstraint("node_id", "rb_content_id"),
    )
    # ### end Alembic commands ###

    # FR-031: four named profiles exist from the start, with no genre tags
    # and no BPM range -- ADR 0008/FR-036 forbid the system having an
    # opinion about what belongs to a booking type, so there is nothing
    # else to seed here; the DJ configures each profile themselves.
    booking_profile = sa.table(
        "booking_profile",
        sa.column("name", sa.String),
        sa.column("slug", sa.String),
    )
    op.bulk_insert(
        booking_profile,
        [
            {"name": "Horeca", "slug": "horeca"},
            {"name": "Bruiloft", "slug": "bruiloft"},
            {"name": "Prive", "slug": "prive"},
            {"name": "Thema", "slug": "thema"},
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("suggestion_dismissal")
    op.drop_table("structure_track")
    op.drop_table("structure_node")
    op.drop_table("structure")
    op.drop_table("booking_profile_genre_tag")
    op.drop_table("booking_profile")
    # ### end Alembic commands ###
