#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — rekordbox-companion onboarding on the real Mac (phase 8 handover,
# docs/process/08-deliver-handover.md step 4). deploy_target is none, so this
# covers running, observing and rolling back -- there is nothing to deploy.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

banner "rekordbox-companion: Mac setup and operations"

# ── Stage 1: prerequisites ─────────────────────────────────────────────────
stage "Prerequisites"
say "Three tools have to be on PATH before anything else works: uv, pnpm (via"
say "corepack) and ffmpeg."
if command -v uv >/dev/null 2>&1; then
  printf '  %s✓%s uv found (%s)\n' "$GREEN" "$RESET" "$(uv --version 2>/dev/null)"
else
  warn "uv not found — install: curl -LsSf https://astral.sh/uv/install.sh | sh"
fi
if command -v pnpm >/dev/null 2>&1; then
  printf '  %s✓%s pnpm found (%s)\n' "$GREEN" "$RESET" "$(pnpm --version 2>/dev/null)"
else
  warn "pnpm not found — install: corepack enable && corepack prepare pnpm@latest --activate"
fi
if command -v ffmpeg >/dev/null 2>&1; then
  printf '  %s✓%s ffmpeg found\n' "$GREEN" "$RESET"
else
  warn "ffmpeg not found — install: brew install ffmpeg"
fi
confirm "All three present (or installed just now)?" || { warn "install the missing tool(s), then re-run this wizard"; exit 1; }

# ── Stage 2: project setup ─────────────────────────────────────────────────
stage "Project setup"
say "This runs 'make setup': uv sync, pnpm install, the Alembic migrations for"
say "the companion's own SQLite store, and the pre-commit hook."
if confirm "Run 'make setup' now?"; then
  ( cd "$(dirname "$0")/.." && make setup )
  printf '  %s✓ done%s\n' "$GREEN" "$RESET"
else
  note "skipped — run 'make setup' by hand before continuing"
  SKIPPED+=("make setup")
fi

# ── Stage 3: Rekordbox itself ───────────────────────────────────────────────
stage "Rekordbox version"
say "This project pins Rekordbox 7.2.17 (ADR 0002, docs/adr/0002-rekordbox-pin-7-2-17.md)."
say "A different installed version does not stop the app running, but"
warn "every guarded write is refused (rb/guard.py) until the version matches,"
warn "and GET /api/health reports version_pin_ok: false until it does."
step "Open Rekordbox, check Help / About for the version number."
step "Rekordbox must have been run at least once already — that is what creates"
step "master.db in the first place. If this is a brand-new install, open"
step "Rekordbox, let it finish its first-run setup, then close it again."
confirm "Rekordbox 7.2.17 is installed and has been run at least once?"

# ── Stage 4: the SQLCipher key ──────────────────────────────────────────────
stage "SQLCipher key"
say "master.db is encrypted. pyrekordbox extracts the key Rekordbox itself uses,"
say "by reading Rekordbox's own installation -- this only works on this Mac,"
say "with Rekordbox actually installed, and cannot be done from a dev container."
if confirm "Run 'pyrekordbox download-key' now?"; then
  ( cd "$(dirname "$0")/../engine" && uv run python -m pyrekordbox download-key )
  printf '  %s✓ done%s\n' "$GREEN" "$RESET"
else
  note "skipped — run it by hand: cd engine && uv run python -m pyrekordbox download-key"
  SKIPPED+=("pyrekordbox download-key")
fi

# ── Stage 5: Spotify developer app ──────────────────────────────────────────
stage "Spotify Developer app"
say "The companion needs its own Spotify app registration. This is a PUBLIC"
say "client using PKCE (specs/001-companion-v1/spec.md, ADR-adjacent decision"
say "in kickoff.md) -- there is no client secret to copy anywhere, ever."
open_url "https://developer.spotify.com/dashboard"
step "Create an app (or open your existing one for this project)."
step "In Settings, add this exact redirect URI:"
note "    http://127.0.0.1:8787/api/auth/spotify/callback"
step "Copy the Client ID from the app's Settings page."
ask SPOTIFY_CLIENT_ID "Paste the Spotify Client ID:"
write_env SPOTIFY_CLIENT_ID "$SPOTIFY_CLIENT_ID"
printf '\n'
warn "Read before syncing a real playlist -- this cost real debugging time once:"
say "A fresh Spotify app starts in Development Mode. In that mode the Web API's"
say "playlist-items endpoint only returns tracks for a playlist THIS account"
say "owns or collaborates on. Adding someone as a tester under User Management"
say "does NOT lift that restriction for playlists they don't own -- a playlist"
say "owned by someone else will always answer a 'playlist_unreachable' error,"
say "by design, not a bug. Sync your own playlists; that is what Development"
say "Mode actually allows."
printf '\n'
warn "Second thing worth knowing: Spotify renamed /playlists/{id}/tracks to"
say "/playlists/{id}/items in a March 2026 migration with no advance notice,"
say "and this app broke silently until that was found and fixed"
say "(engine/src/companion/integrations/spotify.py). If real playlist syncs"
say "start failing again with what looks like a permissions error, check"
say "whether Spotify has changed the API contract again -- compare what"
say "integrations/spotify.py expects against what the API actually returns --"
say "before assuming it is a permissions problem a second time."
pause "Read that? Press Enter to continue."

# ── Stage 6: first run ──────────────────────────────────────────────────────
stage "First run"
say "'make dev' runs both dev servers together. The app binds to 127.0.0.1:8787"
say "only (FR-037) -- on the Mac itself that needs no tunnel, just a browser."
step "In a terminal, from the repo root, run: make dev"
step "Open http://127.0.0.1:8787 in a browser."
step "Connect Spotify from the app's own UI (top bar) -- this is the OAuth"
step "login, separate from the Client ID you just set."
confirm "App loads and Spotify connects?"

# ── Stage 7: observe ────────────────────────────────────────────────────────
stage "Observing the running app"
say "Three places to look when something seems wrong, in this order:"
step "GET /api/health -- status, version_pin_ok, ffmpeg_ok. A degraded status"
step "or version_pin_ok: false points straight at stage 3."
step "The terminal running 'make dev' -- structured JSON log lines for every"
step "guard refusal, backup, Rekordbox write (with its readback verdict), and"
step "sync/enrichment run summary (docs/constraints.md's logging plan)."
step "The app's own UI -- failures are designed to surface as a Dutch message"
step "on screen, not to fail silently (see specs/001-companion-v1/backlog-post-v1.md"
step "for four cases where that discipline caught a real bug)."
note "Full incident detection and notification plan: docs/runbook.md."
pause "Press Enter to continue."

# ── Stage 8: rolling back ───────────────────────────────────────────────────
stage "Rolling back"
say "Two different things can need rolling back, and they are unrelated:"
printf '\n'
step "A bad Rekordbox write: every write is preceded by a timestamped zip"
step "backup (ADR 0016, newest 10 kept). Its path is in both the write's API"
step "response and the log line from stage 7. To restore: close Rekordbox,"
step "unzip the backup, replace master.db (and masterPlaylists6.xml, if the"
step "zip has one) with the backup's copies, reopen Rekordbox."
printf '\n'
step "A bad app version: there is no deployment to roll back (deploy_target:"
step "none, specs/PROFILE.md) -- on the Mac this means 'git checkout' an"
step "earlier commit or tag, then 'make setup && make build && make run' again."
confirm "Understood both rollback paths?"

finish
say "Full operator context: docs/CONTEXT.md (glossary, ADR index, deployment"
say "note) and docs/runbook.md (incidents). Re-run this wizard any time --"
say "it remembers values already saved in .env."
